clear;
clc;
x=readtable("../datos_maiz.csv");
y=x.Last;
figure(1)
plot(x.Date,x.Last) 
% Decompose signal using the EMD

% Generated by MATLAB(R) 23.2 and Wavelet Toolbox 23.2.
% Generated on: 01-Mar-2024 10:56:16

% Logical array for selecting reconstruction elements
levelForReconstruction = [true,true,true,true,true,true];

% Perform the decomposition using EMD
[imf,residual,info] = emd(y, ...
    SiftRelativeTolerance=0.2, ...
    SiftMaxIterations=100, ...
    MaxNumIMF=5, ...
    MaxNumExtrema=1, ...
    MaxEnergyRatio=20, ...
    Interpolation='spline');

% Construct MRA matrix by appending IMFs and residual
mra = [imf residual].';


figure(2)
t = tiledlayout(2,3, ...
    TileSpacing="compact",Padding="compact");
for n = 1:5
    nexttile(t)
    plot(x.Date,imf(:,n))
    title("Modo " + num2str(n))
    xlabel("Tiempo")
end

nexttile(t)
plot(x.Date,residual(:,1))
title('Residuo')
xlabel("Tiempo");
title(t,"Empirical Mode Decomposition (EMD)")
saveas(gcf, 'imagenes/Descompocision_EMD_matrix');

% Sum down the rows of the selected multiresolution signals
y2 = sum(imf(:,4:5),2)+residual;
figure(3)
plot(x.Date,y2, 'Color', 'r')
title("Reconstruccion EMD")
saveas(gcf, 'imagenes/Recosntruccion_EMD');